### ISSUE TITLE
Cannot install crypt3

### ISSUE THREAD

**Issue by evil-shrike** [sendanor/node-crypt3#7]
I'm trying to install Sinopia, which depends on crypt3 which depends on node-gyp. 
Installation fails. How to blame?

```
D:\>npm install -g sinopia
Z:\Prog\nodejs\sinopia -> Z:\Prog\nodejs\node_modules\sinopia\bin\sinopia

> crypt3@0.1.6 install Z:\Prog\nodejs\node_modules\sinopia\node_modules\crypt3
> node-gyp rebuild


Z:\Prog\nodejs\node_modules\sinopia\node_modules\crypt3>node "Z:\Prog\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  crypt3.cc
..\crypt3.cc(6): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory [Z:\Prog\nodejs\node_modules\si nopia\node_modules\crypt3\build\crypt3.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (Z:\Prog\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "Z:\\Prog\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd Z:\Prog\nodejs\node_modules\sinopia\node_modules\crypt3
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "Z:\\Prog\\nodejs\\\\node.exe" "Z:\\Prog\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "sinopia"
npm ERR! node v0.10.26
npm ERR! npm  v2.1.9
npm ERR! code ELIFECYCLE

npm ERR! crypt3@0.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the crypt3@0.1.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the crypt3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls crypt3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Work\R-n-D\XFW3_WebClient_doc\npm-debug.log
```

**Comment by ppalladino** [comment]
I am having the same issue. Any resolution?

**Comment by DennisBecker** [comment]
II'm also having this issue on a Debian Wheezy machine.

**Comment by jheusala** [comment]
Well, we could silently build dummy Windows version that just throws an exception but I don't think that is correct fix. 

I've also had these problems with NPM forcing optional packages and I don't know how to fix that. Sounds like bug in NPM but if that's not true, somebody smarter could explain why it is so.

**Comment by petershaw** [comment]
i still have problems on this issue. Can't install sinopia. Does you solved the problem?

**Comment by cheristi** [comment]
Same issue here, Windows 7. 

Under Ubuntu it runs out of the box. Would be nice to have the same experience under windows :)

**Comment by jheusala** [comment]
Windows does not have the `crypt(3)` function, so we cannot have same experience under windows.

However some people have reported install issues on Debian, where this should work. Please open another issue about those -- this issue is about non-working Windows support.
